apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name:  mysqlclusters.mysql.middleware.harmonycloud.cn
  labels:
    MiddlewareCluster: mysqlcluster
spec:
  group: mysql.middleware.harmonycloud.cn
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  names:
    kind: MysqlCluster
    listKind: MysqlClusterList
    plural: mysqlclusters
    shortNames:
      - mc
    singular: mysqlcluster
  scope: Namespaced
