apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "elasticsearch-operator.fullname" . }}
  labels:
    {{- include "elasticsearch-operator.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "elasticsearch-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole 
  name: {{ include "elasticsearch-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "elasticsearch-operator.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "elasticsearch-operator.fullname" . }}
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - statefulsets
  - deployments
  - daemonsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - es.middleware.hc.cn 
  resources:
  - esclusters
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create
- apiGroups:
  - es.middleware.hc.cn 
  resources:
  - esclusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - create

