global:
  repository: harbor.middleware.com/middleware
  middleware_controller:
    image: middleware-controller
    tag: v1.2.5
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
  middlewarebackup_controller:
    image: middlewarebackup-controller
    tag: v1.1.2
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 512Mi
    nodeSelector: {}
    job_creator:
      jobNamespace: middleware-job
      jobServiceAccount: job-creator
      image: backup-job-creator
      tag: v1.0.1
    common_path_backup:
      image: middleware-backup-operator
      tag: v1.0.0-common
    job_pgsql_backup:
      image: middleware-backup-operator
      tag: v1.0.0-pgsql
  kubectl:
    installCRDs: true
    tag: 1.21
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
    nodeSelector: {}
    tolerations: []
    affinity: {}