apiVersion: v1
kind: Service
metadata:
  name: zeus-ui-svc
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - name: port-30088
    nodePort: {{ .Values.global.zeus_ui.nodePort }}
    port: 30088
    protocol: TCP
    targetPort: 30088
  - name: port-30488
    port: 30488
    protocol: TCP
    targetPort: 30488
    nodePort: 31488
  selector:
    app: zeus-ui
  sessionAffinity: None
  type: NodePort
