apiVersion: v1
stringData:
  endpoint: {{ .Release.Name }}-svc.{{ .Release.Namespace }}.svc
  port: "{{ .Values.service.port }}"
  username: {{ .Values.accessKey }}
  password: "{{ .Values.secretKey }}"
kind: Secret
metadata:
  name: {{ .Release.Name }}-credential
  namespace: {{ .Release.Namespace }}
type: Opaque