{{- if  .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ include "minio.fullname" . }}
    {{- include "minio.labels" . | nindent 4 }}
  name: {{ include "minio.fullname" . }}
spec:
  endpoints:
  - interval: 30s
    port: http-metrics
    path: /minio/prometheus/metrics
  jobLabel: app
  selector:
    matchLabels:
      app: {{ include "minio.fullname" . }}-metrics
{{- end }}
